version: '3.5'
services:

  selenium-hub:
    image: 'selenium/hub:3.14'
    container_name: 'selenium-hub'
    shm_size: '2gb'
    volumes:
      # - '/dev/shm:/dev/shm'
      # Needed for Behat file uploads (Must be the same as in php app container)
      - './volumes/app:${APP_PATH}:ro,cached'
    environment:
      SCREEN_WIDTH: 2880
      SCREEN_HEIGHT: 1800
    expose:
     - 4444
    networks:
     - 'sylius'
    restart: 'always'

  selenium-chrome:
    # Travis version: selenium/node-chrome:3.8.1-dubnium
    image: 'selenium/node-chrome:3.14'
    container_name: 'selenium-chrome'
    shm_size: '2gb'
    volumes:
      # - '/dev/shm:/dev/shm'
      # Needed for Behat file uploads (Must be the same as in php app container)
      - './volumes/app:${APP_PATH}:ro,cached'
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      SCREEN_WIDTH: 2880
      SCREEN_HEIGHT: 1800
    expose:
      - 5555
    networks:
     - 'sylius'
    restart: 'always'
    depends_on:
      - selenium-hub
