version: '3.5'
services:

  nginx:
    image: 'nginx:1.15-alpine'
    container_name: 'nginx'
    command: /bin/sh -c "envsubst '$$APP_PUBLIC_PATH' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - './volumes/app:${APP_PATH}:ro'
      - './volumes/nginx/logs:/var/log/nginx:rw,delegated'
      # Config
      - './images/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template'
    environment:
      APP_PUBLIC_PATH: ${APP_PUBLIC_PATH}
    ports:
     - 80:80
    networks:
     - 'sylius'
    restart: 'always'
    depends_on:
      - php

  php:
    # Based on: 'php:7.2-fpm-alpine3.8'
    build:
      context: './images/php'
    container_name: 'php'
    volumes:
      # App
      - './volumes/app:${APP_PATH}:rw,cached'
      # PHP Config
      - './images/php/00-user.ini:/usr/local/etc/php/conf.d/00-user.ini'
      - './images/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    environment:
      # Symfony Dotenv never overwrites existing environment variables
      APP_PATH: ${APP_PATH}
      # APP_ENV: dev
      # APP_DEBUG: 1
      APP_SECRET: EDITME
      DATABASE_URL: mysql://root:root@mysql/sylius_%kernel.environment%
      MAILER_URL: smtp://mailhog:1025
      # *.ini
      PHP_DATE_TIMEZONE: UTC
      PHP_SESSIONS_SAVE_PATH: /usr/local/php/sessions
      # We need to set a high memory limit to build sucessfully
      PHP_MEMORY_LIMIT: 2G
      PHP_XDEBUG_REMOTE_HOST: 172.20.0.1
      PHP_XDEBUG_REMOTE_PORT: 9000
    expose:
      - 9000
    networks:
     - 'sylius'
    restart: 'always'
    depends_on:
      - mysql

  mysql:
    image: 'mysql:5.7'
    container_name: 'mysql'
    volumes:
      - './volumes/mysql/databases:/var/lib/mysql:rw,delegated'
      - './volumes/mysql/logs:/var/log/mysql:rw,delegated'
      # Config
      - './images/mysql/user.cnf:/etc/mysql/conf.d/user.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    networks:
     - 'sylius'
    restart: 'always'

  selenium-hub:
    image: 'selenium/hub:3.14'
    container_name: 'selenium-hub'
    shm_size: '2gb'
    volumes:
      # - '/dev/shm:/dev/shm'
      # Needed for Behat file uploads (Must be the same as in php app container)
      - './volumes/app:${APP_PATH}:ro,cached'
    environment:
      SCREEN_WIDTH: 2880
      SCREEN_HEIGHT: 1800
    expose:
     - 4444
    networks:
     - 'sylius'
    restart: 'always'

  selenium-chrome:
    # Travis version: selenium/node-chrome:3.8.1-dubnium
    image: 'selenium/node-chrome:3.14'
    container_name: 'selenium-chrome'
    shm_size: '2gb'
    volumes:
      # - '/dev/shm:/dev/shm'
      # Needed for Behat file uploads (Must be the same as in php app container)
      - './volumes/app:${APP_PATH}:ro,cached'
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      SCREEN_WIDTH: 2880
      SCREEN_HEIGHT: 1800
    expose:
      - 5555
    networks:
     - 'sylius'
    restart: 'always'
    depends_on:
      - selenium-hub

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: 'mailhog'
    volumes:
      - './volumes/mailhog/maildir:/maildir:rw,delegated'
    environment:
      MH_STORAGE: maildir
    ports:
      # Web interface port
      - 8025:8025
    expose:
      # SMTP port
      - 1025
    networks:
     - 'sylius'
    restart: 'always'

  adminer:
    image: 'adminer:standalone'
    container_name: 'adminer'
    command: php -S [::]:8033 -t /var/www/html
    environment:
      ADMINER_PORT: 8033
    ports:
      - 8033:8033
    networks:
     - 'sylius'
    restart: 'always'
    depends_on:
      - mysql

networks:
  sylius:
    name: 'sylius'
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
